raw_data_path                   : data/raw/common_voice/
split_ratio                     : 0.3
sampling_rate                   : 16000


training_args:
  output_dir: model/
  group_by_length: true
  gradient_checkpointing: true
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 2
  evaluation_strategy: steps
  max_steps: 50
  fp16: true
  save_steps: 10
  eval_steps: 10
  logging_steps: 10
  learning_rate: 0.000001
  weight_decay: 0.005
  warmup_steps: 25
  save_total_limit: 2
  load_best_model_at_end: true         
  metric_for_best_model: wer
  greater_is_better: False  